In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style='white', color_codes=True)

In [ ]:
df=pd.read_csv('/train.csv/')

FileNotFoundError: ignored

In [ ]:
df.head()

Organization Group Code Job Family Code  ... Total Benefits Total Compensation
0                        1            1000  ...       27747.13           85281.78
1                        1            1000  ...       22216.82           79895.32
2                        1            1000  ...       30116.78           93649.71
3                        1            1000  ...       40021.45          134237.37
4                        1            1000  ...        2428.31            7512.31

[5 rows x 22 columns]

In [ ]:
df.shape

(471059, 22)

In [ ]:
df.tail()

Organization Group Code  ... Total Compensation
471054                        1  ...           45788.85
471055                        1  ...           47471.11
471056                        1  ...          167753.34
471057                        1  ...           29449.96
471058                        1  ...                NaN

[5 rows x 22 columns]

In [ ]:
df.describe()

Organization Group Code  ...  Total Compensation
count            471059.000000  ...       471058.000000
mean                  2.953152  ...       104050.448791
std                   1.583309  ...        70778.461860
min                   1.000000  ...       -74082.610000
25%                   2.000000  ...        41526.610000
50%                   2.000000  ...       104350.745000
75%                   4.000000  ...       150040.290000
max                   7.000000  ...       724031.060000

[8 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471059 entries, 0 to 471058
Data columns (total 22 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   Organization Group Code  471059 non-null  int64  
 1   Job Family Code          471059 non-null  object 
 2   Job Code                 471059 non-null  object 
 3   Year Type                471059 non-null  object 
 4   Year                     471059 non-null  int64  
 5   Organization Group       471059 non-null  object 
 6   Department Code          471059 non-null  object 
 7   Department               471059 non-null  object 
 8   Union Code               470880 non-null  float64
 9   Union                    470880 non-null  object 
 10  Job Family               471058 non-null  object 
 11  Job                      471057 non-null  object 
 12  Employee Identifier      471058 non-null  float64
 13  Salaries                 471058 non-null  float64
 14  Over

In [ ]:
miss_val = df.isna().sum()
miss_val

Organization Group Code      0
Job Family Code              0
Job Code                     0
Year Type                    0
Year                         0
Organization Group           0
Department Code              0
Department                   0
Union Code                 179
Union                      179
Job Family                   1
Job                          2
Employee Identifier          1
Salaries                     1
Overtime                     1
Other Salaries               1
Total Salary                 1
Retirement                   1
Health and Dental            1
Other Benefits               1
Total Benefits               1
Total Compensation           1
dtype: int64

In [ ]:
col_name=df.columns
for i in col_name:
    print(i,'has :',df[i].nunique(),"Unique values")

Organization Group Code has : 7 Unique values
Job Family Code has : 59 Unique values
Job Code has : 1194 Unique values
Year Type has : 2 Unique values
Year has : 7 Unique values
Organization Group has : 7 Unique values
Department Code has : 60 Unique values
Department has : 107 Unique values
Union Code has : 70 Unique values
Union has : 128 Unique values
Job Family has : 59 Unique values
Job has : 1332 Unique values
Employee Identifier has : 181838 Unique values
Salaries has : 347866 Unique values
Overtime has : 184111 Unique values
Other Salaries has : 227431 Unique values
Total Salary has : 430168 Unique values
Retirement has : 320035 Unique values
Health and Dental has : 147715 Unique values
Other Benefits has : 369476 Unique values
Total Benefits has : 436411 Unique values
Total Compensation has : 458398 Unique values


In [ ]:
df['Employee Identifier'].fillna(0.0, inplace=True)
df['Salaries'].fillna(0.0, inplace=True)
df['Overtime'].fillna(0.0, inplace=True)
df['Other Salaries'].fillna(0.0, inplace=True)
df['Total Salary'].fillna(0.0, inplace=True)
df['Retirement'].fillna(0.0, inplace=True)
df['Health and Dental'].fillna(0.0, inplace=True)
df['Other Benefits'].fillna(0.0, inplace=True)
df['Total Benefits'].fillna(0.0, inplace=True)
df['Total Compensation'].fillna(0.0, inplace=True)
df['Union Code'].fillna(0.0, inplace=True)
df['Union'].fillna("unknown", inplace=True)
df['Department Code'].fillna('uuu', inplace=True)
df['Department'].fillna('unknown', inplace=True)
df['Job'].fillna("unknown", inplace=True)

In [ ]:
df['Organization Group Code'].value_counts()

2    147369
4    101997
1     94543
3     42424
5     42179
6     42156
7       391
Name: Organization Group Code, dtype: int64

In [ ]:
df['Organization Group Code'].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
df['Job Family Code'].value_counts()

2300              48389
9100              38814
Q000              30162
7300              27359
2900              23843
9900              22743
1400              20726
H000              20574
2700              15136
0900              14828
8200              13851
3200              13590
5200              13490
1800              13406
8300              12628
1000              11216
8100              10933
1600               9586
2500               9533
3600               8495
2400               7953
1200               6855
5300               6186
7500               6121
SCRT               5323
3400               5044
9200               4635
7200               4542
7400               4039
2200               3623
9700               3405
2600               3355
0000               2587
1900               2577
6300               2508
8400               2344
4200               2114
5600               1952
1300               1951
2800               1942
2100               1804
1700            

In [ ]:
df["Job Family Code"].replace("SCRT","0000",inplace=True)
df["Job Family Code"].replace("H000","0001",inplace = True)
df["Job Family Code"].replace("Q000","0002", inplace=True)
df["Job Family Code"].replace("SFRA","0003", inplace=True)
df["Job Family Code"].replace("__UNASSIGNED__","0004", inplace=True)

In [ ]:
df['Job Family Code'].unique()

array(['1000', '1200', '1600', '1800', '1400', '0900', '8400', '9700',
       '9900', '0000', '8100', '1500', '5200', '8200', '8600', '2500',
       '1900', '6200', '2200', '2100', '2300', '0001', '0002', '7100',
       '7200', '7300', '2600', '2700', '7500', '8300', '2900', '1300',
       '7400', '1700', '3300', '9200', '3400', '2400', '5100', '5300',
       '5500', '5600', '6100', '6300', '9300', '3500', '3600', '4300',
       '5400', '9100', '4100', '2800', '4200', '1100', '3200', '0003',
       '0004', '9500'], dtype=object)

In [ ]:
df['Job Code'].unique()

array(['1021', '1023', '1031', ..., '3502', '3246', '1367'], dtype=object)

In [ ]:
df['Job Code'].unique()

array(['1021', '1023', '1031', ..., '3502', '3246', '1367'], dtype=object)

In [ ]:
df["Job Code"].replace("351C","3510",inplace=True)

In [ ]:
df['Year Type'].unique()

array(['Calendar', 'Fiscal'], dtype=object)

In [ ]:
df['Year Type'].value_counts()

Calendar    298164
Fiscal      172895
Name: Year Type, dtype: int64

In [ ]:
df['Year'].unique()

array([2013, 2014, 2015, 2016, 2017, 2018, 2019])

In [ ]:
df['Organization Group'].unique()

array(['Public Protection', 'Public Works, Transportation & Commerce',
       'Human Welfare & Neighborhood Development', 'Community Health',
       'Culture & Recreation', 'General Administration & Finance',
       'General City Responsibilities'], dtype=object)

In [ ]:
df['Department Code'].unique()

array(['ADP', 'CRT', 'DAT', 'ECD', 'FIR', 'JUV', 'PDR', 'POL', 'SHF',
       'AIR', 'CWP', 'DBI', 'DPW', 'ECN', 'HHP', 'MTA', 'PAB', 'PRT',
       'PUC', 'WTR', 'CFC', 'CHF', 'CII', 'CSS', 'DSS', 'ENV', 'HRC',
       'RNT', 'WOM', 'DPH', 'AAM', 'ART', 'FAM', 'LIB', 'LLB', 'REC',
       'SCI', 'WAR', 'ADM', 'ASR', 'BOS', 'CAT', 'CON', 'CPC', 'CSC',
       'ETH', 'HRD', 'HSS', 'MYR', 'REG', 'RET', 'TIS', 'TTX', 'UNA',
       'CLP', 'HOM', 'DEM', 'DPA', 'BOA', 'HSA'], dtype=object)

In [ ]:
df['Department Code'].unique()

array(['ADP', 'CRT', 'DAT', 'ECD', 'FIR', 'JUV', 'PDR', 'POL', 'SHF',
       'AIR', 'CWP', 'DBI', 'DPW', 'ECN', 'HHP', 'MTA', 'PAB', 'PRT',
       'PUC', 'WTR', 'CFC', 'CHF', 'CII', 'CSS', 'DSS', 'ENV', 'HRC',
       'RNT', 'WOM', 'DPH', 'AAM', 'ART', 'FAM', 'LIB', 'LLB', 'REC',
       'SCI', 'WAR', 'ADM', 'ASR', 'BOS', 'CAT', 'CON', 'CPC', 'CSC',
       'ETH', 'HRD', 'HSS', 'MYR', 'REG', 'RET', 'TIS', 'TTX', 'UNA',
       'CLP', 'HOM', 'DEM', 'DPA', 'BOA', 'HSA'], dtype=object)

In [ ]:
df['Department'].unique()

array(['ADP Adult Probation', 'CRT Superior Court',
       'DAT District Attorney', 'DEM Emergency Management',
       'FIR Fire Department', 'JUV Juvenile Probation',
       'PDR Public Defender', 'POL Police', 'SHF Sheriff',
       'AIR Airport Commission', 'WWE Wastewater Enterprise',
       'DBI Building Inspection', 'DPW GSA - Public Works',
       'ECN Economic & Wrkfrce Dvlpmnt', 'HHP Hetch Hetchy Water & Power',
       'MTA Municipal Transprtn Agncy', 'BOA Board Of Appeals - PAB',
       'PRT Port', 'PUB Public Utilities Bureaus', 'WTR Water Enterprise',
       'CFC Children & Families Commsn', 'CHF Children;Youth & Families',
       'CII Commty Invest & Infrstrctr', 'CSS Child Support Services',
       'HSA Human Services Agency', 'ENV Environment',
       'HRC Human Rights Commission', 'RNT Rent Arbitration Board',
       'WOM Status Of Women', 'DPH Public Health', 'AAM Asian Art Museum',
       'ART Arts Commission', 'FAM Fine Arts Museum',
       'LIB Public Library', 'LLB 

In [ ]:
df['Union'].unique()

array(['Prof & Tech Engineers - Miscellaneous, Local 21',
       'Prof & Tech Engineers - Personnel, Local 21',
       'Municipal Executive Association - Miscellaneous',
       "Deputy Probation Officers' Association",
       'SEIU - Miscellaneous, Local 1021',
       'Operating Engineers - Sup Probation Ofcrs, Local 3',
       'Prof & Tech Engineers - Court Employees, Local 21',
       'Prof & Tech Engineers - Court Attorneys, Local 21',
       'Court Interpreters, Local 39521',
       'Court Unrepresented Professionals',
       'Court Unrepresented Managers',
       'Prof & Tech Engineers - Court Reporters, Local 21',
       'Municipal Executive Association - Court',
       'SEIU - Court Employees, Local 1021',
       'Court Unrepresented Bench Officers',
       'Management Unrepresented Employees',
       "Municipal Attorneys' Association",
       "District Attorney Investigators' Association",
       'Elected Officials', 'Miscellaneous Unrepresented Employees',
       'Physicians a

In [ ]:
df['Union'].unique()

array(['Prof & Tech Engineers - Miscellaneous, Local 21',
       'Prof & Tech Engineers - Personnel, Local 21',
       'Municipal Executive Association - Miscellaneous',
       "Deputy Probation Officers' Association",
       'SEIU - Miscellaneous, Local 1021',
       'Operating Engineers - Sup Probation Ofcrs, Local 3',
       'Prof & Tech Engineers - Court Employees, Local 21',
       'Prof & Tech Engineers - Court Attorneys, Local 21',
       'Court Interpreters, Local 39521',
       'Court Unrepresented Professionals',
       'Court Unrepresented Managers',
       'Prof & Tech Engineers - Court Reporters, Local 21',
       'Municipal Executive Association - Court',
       'SEIU - Court Employees, Local 1021',
       'Court Unrepresented Bench Officers',
       'Management Unrepresented Employees',
       "Municipal Attorneys' Association",
       "District Attorney Investigators' Association",
       'Elected Officials', 'Miscellaneous Unrepresented Employees',
       'Physicians a

In [ ]:
df['Union Code'].unique()

array([ 21.,  22., 351., 651., 790., 965.,  23., 121., 191., 195., 196.,
       197., 356., 792., 933.,   2., 311., 419., 556.,   1., 163., 164.,
       323., 352., 791., 793., 798., 799., 911.,  39., 250., 535., 856.,
       200., 252., 353.,   6.,  38., 261., 498., 499., 969.,   3.,   4.,
         7., 104., 130., 216., 236., 251., 930., 929.,  12.,  36., 253.,
       580., 718., 254., 302.,  34.,  40., 377., 604., 330., 990., 858.,
        16., 220., 257.,   0., 357.])

In [ ]:
df['Union Code'].value_counts()

790.0    132882
21.0      60129
791.0     35591
911.0     30251
253.0     29351
          ...  
220.0        24
969.0        17
302.0        11
604.0        10
357.0         6
Name: Union Code, Length: 71, dtype: int64

In [ ]:
df['Job Family'].unique()

array(['Information Systems', 'Personnel',
       'Payroll, Billing & Accounting', 'Budget, Admn & Stats Analysis',
       'Clerical, Secretarial & Steno', 'Management',
       'Probation & Parole', 'Community Development',
       'Public Service Aide', 'SF Superior Court', 'Legal & Court',
       'Administrative Secretarial', 'Professional Engineering',
       'Protection & Apprehension', 'Emergency Services',
       'Med Therapy & Auxiliary', 'Purchasing & Storekeeping',
       'Public Safety Inspection', 'Medical & Dental',
       'Hospital Administration', 'Nursing', 'Fire Services',
       'Police Services', 'Administrative-Labor & Trades',
       'Supervisory-Labor & Trade', 'Journeyman Trade', 'Dietary & Food',
       'Housekeeping & Laundry', 'Semi-Skilled & General Labor',
       'Correction & Detention', 'Human Services',
       'Pub Relations & Spec Assts', 'Skilled Labor',
       'Computer Operatns & Repro Svcs', 'Park & Zoo',
       'Airport Operation', 'Agriculture & Hort

In [ ]:
df['Job'].unique()

array(['IS Administrator 1', 'IS Administrator 3', 'IS Trainer-Assistant',
       ..., 'Special Assistant 8', 'Commissioner 16700c, No Pay',
       'Assistant Chief Of Police'], dtype=object)

In [ ]:
df['Employee Identifier'].unique()

array([37730., 26574.,  8148., ..., 39880.,  4077., 41709.])

In [ ]:
df_num = df.select_dtypes(include = ['object',])
df_num.head()

Job Family Code Job Code  ...           Job Family                            Job
0            1000     1021  ...  Information Systems             IS Administrator 1
1            1000     1023  ...  Information Systems             IS Administrator 3
2            1000     1031  ...  Information Systems           IS Trainer-Assistant
3            1000     1054  ...  Information Systems  IS Business Analyst-Principal
4            1000     1062  ...  Information Systems          IS Programmer Analyst

[5 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['Job Family Code1']=le.fit_transform(df['Job Family Code'])
df['Job Code1']=le.fit_transform(df['Job Code'])
df['Year Type1']=le.fit_transform(df['Year Type'])
df['Organization Group1']=le.fit_transform(df['Organization Group'])
df['Department Code1']=le.fit_transform(df['Department Code'])
df['Department1']=le.fit_transform(df['Department'])
df['Union1']=le.fit_transform(df['Union'])
df['Job Family1']=le.fit_transform(df['Job Family'])
df['Job1']=le.fit_transform(df['Job'])

TypeError: ignored

In [ ]:
df.drop(['Job Family Code'],axis=1,inplace=True)
df.drop(['Job Code'],axis=1,inplace=True)
df.drop(['Year Type'],axis=1,inplace=True)
df.drop(['Organization Group'],axis=1,inplace=True)
df.drop(['Department Code'],axis=1,inplace=True)
df.drop(['Department'],axis=1,inplace=True)
df.drop(['Union'],axis=1,inplace=True)
df.drop(['Job Family'],axis=1,inplace=True)
df.drop(['Job'],axis=1,inplace=True)

In [ ]:
df.head()

In [ ]:
sns.distplot(df['Total Benefits'])
plt.show()

In [ ]:
sns.distplot(df['Total Compensation'])
plt.show()

In [ ]:
print("Skewness: %f" % df['Total Compensation'].skew())
print("Kurtosis: %f" % df['Total Compensation'].kurt())

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans=KMeans(n_clusters=3)

In [ ]:
df.columns

In [ ]:
X = df.drop(['Organization Group Code', 'Union Code', 'Employee Identifier',
       'Salaries', 'Overtime', 'Other Salaries', 'Retirement',
       'Health and Dental', 'Other Benefits', 'Total Benefits',
       'Job Family Code1', 'Job Code1', 'Year Type1',
       'Organization Group1', 'Department Code1', 'Department1', 'Union1',
       'Job Family1', 'Job1'], axis=1)
display(X)
      



In [ ]:
kmeans.fit(X)

In [ ]:
print(kmeans.cluster_centers_)

In [ ]:
y=kmeans.labels_
print(y)

In [ ]:
sns.countplot(x=kmeans.labels_, palette='Oranges')
plt.show()

In [ ]:
plt.scatter(df.iloc[:,0].values,df.iloc[:,3].values, c=kmeans.labels_, cmap="rainbow")
plt.show()

In [ ]:
centers = np.array(kmeans.cluster_centers_)
plt.scatter(centers[:,0], centers[:,1], marker="x", color='k')

In [ ]:
plt.scatter(df.iloc[:,0].values,df.iloc[:,3].values, c=kmeans.labels_, cmap="rainbow")
centers = np.array(kmeans.cluster_centers_)
plt.scatter(centers[:,0], centers[:,1], marker="x", color='k')
plt.show()

In [ ]:
from scipy.spatial.distance import cdist, pdist
from sklearn.cluster import KMeans

In [ ]:
#K = range(1,10)
#X = df.drop(['Organization Group Code', 'Union Code', 'Employee Identifier',
    #   'Salaries', 'Overtime', 'Other Salaries', 'Retirement',
     #  'Health and Dental', 'Other Benefits', 'Total Benefits',
      # 'Job Family Code1', 'Job Code1', 'Year Type1',
       #'Organization Group1', 'Department Code1', 'Department1', 'Union1',
       #'Job Family1', 'Job1'], axis=1)
#KM = [KMeans(n_clusters=k,verbose=1).fit(X) for k in K]
#centroids = [k.cluster_centers_ for k in KM]
#D_k = [cdist(X, cent, 'euclidean') for cent in centroids]
#cIdx = [np.argmin(D,axis=1) for D in D_k]
#dist = [np.min(D,axis=1) for D in D_k]
#avgWithinSS = [sum(d)/X.shape[0] for d in dist]

In [ ]:
#Total with-in sum of square
#wcss = [sum(d**2) for d in dist]
#tss = sum(pdist(X)**2)/X.shape[0]
#3bss = tss-wcss
# varExplained = bss/tss*100

In [ ]:
sse = {}
for k in range(1, 10):
    kmeans = KMeans(n_clusters=k, max_iter=1000).fit(X)
    sse[k] = kmeans.inertia_ # Inertia: Sum of distances of samples to their closest cluster center
plt.figure()
plt.plot(list(sse.keys()), list(sse.values()))
plt.xlabel("Number of cluster")
plt.ylabel("SSE")
plt.show()

In [ ]:
import scipy
from scipy.cluster.hierarchy import dendrogram,linkage
from scipy.cluster.hierarchy import fcluster
from scipy.cluster.hierarchy import cophenet
from scipy.spatial.distance import pdist

In [ ]:
from pylab import rcParams
from sklearn.cluster import AgglomerativeClustering
import sklearn.metrics as sm

In [ ]:
plt.style.available

In [ ]:
plt.style.use('seaborn-whitegrid')

In [ ]:
df.head()

In [ ]:
plt.figure(figsize=(15,10))
Z=linkage(df.drop(['Total Compensation'],axis=1),method='complete')
print("Z-Shape:",Z.shape)
plt.title("COMPLETE",size=30)
dendrogram(Z,orientation='top',truncate_mode='lastp',p=12,get_leaves=False,leaf_rotation=45,leaf_font_size=15,show_contracted=True,)
plt.xlabel("Cluster Size",fontsize=30)
plt.ylabel("Distances",fontsize=30)
plt.show()

In [ ]:
plt.figure(figsize=(15,10))
Z=linkage(df.drop(['Total Compensation'],axis=1),method='weighted')
print("Z-Shape:",Z.shape)
plt.title("Weighted",loc='center',size=30)
dendrogram(Z,orientation='top',truncate_mode='lastp',p=12,get_leaves=False,leaf_rotation=45,leaf_font_size=15,show_contracted=True,)
plt.xlabel("Cluster Size",fontsize=30)
plt.ylabel("Distances",fontsize=30)
plt.show()